### ISSUE TITLE
broken in 0.7.0-alpha

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#12]
```
Error: Undefined class constant 'TYPE_RESOURCE' in /var/www/omekas/modules/MetadataBrowse/Module.php:108
Stack trace:
#0 [internal function]: MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#1 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\EventManager\Event))
#2 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('rep.value.html', Object(Zend\EventManager\Event), NULL)
#3 /var/www/omekas/application/src/Api/Representation/ValueRepresentation.php(56): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#4 /var/www/omekas/application/view-shared/common/resource-values.phtml(37): Omeka\Api\Representation\ValueRepresentation->asHtml()
#5 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/var/www/omekas...')
#6 /var/www/omekas/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(Array)
#7 /var/www/omekas/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(401): Zend\View\Helper\Partial->__invoke('common/resource...', Array)
#8 /var/www/omekas/application/view-admin/omeka/admin/item/show.phtml(31): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#9 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/var/www/omekas...')
#10 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#11 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#13 /var/www/omekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#15 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(251): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent))
#17 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#18 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#19 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#20 {main}
```

**Comment by zerocrates** [comment]
Those constants are gone: a consequence of the introduction of Data Types.

You could easily replace these with their string name equivalents, but I think there's a bit of an open question as to how this should actually interact with the data types. Just translating the constants to strings works for the built-in 3, but a Custom Vocab value wouldn't work as it has a different type name.

**Comment by patrickmj** [comment]
thanks. I'd figured on the quick switch to string equivalents, but hadn't thought of the Custom Vocab quirk.

**Comment by zerocrates** [comment]
One possible solution to that problem is to look at what's stored in the Value rather than its type (or maybe just in the case where you don't recognize the type name): If the linked internal resource is set, treat it that way, if the URL is set treat it like a URL, if the text value is set treat it like a literal.

That will work for our current types anyway, as they're so far just veneers over the regular ones. We could do some stuff to the Data Types themselves to make this more workable for more exotic types, but I'm not sure whether that's wise or not.

Alternatively, instead of a switch-type structure MetadataBrowse could maintain basically a registry of "how do I search for this type" for each type in its module config, shifting the responsibility for accounting for MetadataBrowse-ability onto the module that added the Data Type itself.

Side note: the URL search will also currently be broken because the search won't match a URL.

**Comment by patrickmj** [comment]
Looks like anything but literal search is broken.

The registry sounds like the most reasonable option to me, especially as we've gone an analogous route with CSVImport

**Comment by zerocrates** [comment]
Resources _should_ still be working, that's be an unexpected bug if they've been broken as well.

**Comment by patrickmj** [comment]
Yep. broken. Looks like this line https://github.com/omeka-s-modules/MetadataBrowse/blob/develop/Module.php#L109 which gets an undefined index notice

**Comment by zerocrates** [comment]
Oh yeah that's an even older change: the event only passes 'html'. You want to access the other stuff by just calling the regular representation methods on $target.

**Comment by patrickmj** [comment]
In the world of modules adding their own search through adding to a config setting, would that look like a special class they create that adds onto the HTML? Or maybe just builds the `$searchUrl` and somehow that gets stuffed in?

Currently the switch just adds onto the passed-in HTML like this, after building the `$searchUrl` for each datatype

``` php
            $text = $translator->translate('See all items with this value');
            $link = "<a href='$searchUrl'>$text</a>";
            $event->setParam('html', "$html $link");
```

**Comment by patrickmj** [comment]
The SearchUrl branch goes with the modules adding their thing for search urls via config. Classes that implement SearchUrlInterface should be able to do that.

Need to decide whether to go with this route, or simplify down to the basic switch. Thoughts, @zerocrates , @jimsafley ?

**Comment by zerocrates** [comment]
I'm leaning toward the "switch" or "guess"-type option we talked about.

**Comment by patrickmj** [comment]
So, basically what's in develop now?

**Comment by zerocrates** [comment]
The "guess" implies a default case that looks at the Value to decide amongst the three search options based on what's stored on the value.

**Comment by patrickmj** [comment]
OK. will see what happens
