### ISSUE TITLE
Make appearance of the link out icon consistent

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#14]
Probably needs @kimisgold's insight here. The added link to search by a value changes the added icon based on the type. In the example below, dcterms:title does a search on the literal value, and description has an external url value to example.com. (this is on the SearchUrl branch of MetadataBrowse).

I think we just need to work out the selectors for where the pointy-outy arrow icon appears or doesn't appear. 

![urllinky](https://cloud.githubusercontent.com/assets/153262/17085256/fed4ced2-51a1-11e6-9a06-66818863f458.png)

**Comment by kimisgold** [comment]
I added some styles here (95e0419b8fe0f092d62ff70b8c0e69173ff8cf77), but I didn't know how to append the `metadata-browse.css` file to the head of that view.
