### ISSUE TITLE
Feedback on admin settings

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#19]
Planning convo leaned toward making admin side links be a global config setting. After putting that back in, I'm more hesitant about whether that makes sense.

The question is, what behavior makes most sense on the admin side: linked properties are set specifically for the admin side as global config settings for the module, or linked properties are an aggregate of the settings each site creates.

To test this, you'll want an installation with a couple different sites, each with different MetadataBrowse settings for which properties create links. (obviously, you'll want data for all those properties on some items)

Ideally, if many people on the testing team have their own installations, a little role playing will make sense, with one person playing the role of global admin, not knowing what the site settings for MetadataBrowse are.

In the module configuration, a global admin can choose whether to use global settings for admin, or use the aggregate. You can switch back and forth whenever you want. On the global admin option, they create their own settings.

Use the latest on the admin-options branch.

**Comment by mebrett** [comment]
For the purposes of evaluation (since not everyone testing was in planning): Metadata Browse functions in a similar way to Omeka Classic's Search by Metadata. 

By "global config settings for the module" you mean that linked properties are consistent across all sites, or that the global admin would enable the module for certain properties, which site admins could then enable or disable per site?

**Comment by patrickmj** [comment]
The key thing is that this question is just for the admin side, so it's not really a matter of consistency across sites. It's more a matter of what makes sense for admins adminning on the admin side. 

The global config, as set on the module's config page would only apply to the admin side, and would ignore all the sites' settings. That is, there's no sense of global admins enabling or disabling properties for sites. Rather, sites can always do their own thing with the metadata browse properties -- global settings won't affect anything on the site level.

It's a question of what makes more sense on the admin side, where sites aren't in play -- create the links based on the aggregate of what all the sites have done, or create links based on what a global admin has decided are the linked properties in the module's config.

**Comment by mebrett** [comment]
The discussion I had with Jannlle and Alyssa indicated that we could see the virtue of both options. 

Personally I like having it be a setting, with the default to aggregate, not global, partly because each of the sites/site admins was using different properties in very different ways. 

I'm going to check in with my fellow testers on Monday before planning, and will report back.

**Comment by sheilabrennan** [comment]
Can this helper text be clarified, found under "Use global configuration on admin side"

"If checked, the properties set below will be made links on the admin side. Otherwise, all properties made links in all sites will be links on the admin side."

This text is really hard to understand.

**Comment by patrickmj** [comment]
@sheilabrennan how's this?

> This controls which properties become links on the admin side -- whether to use the settings here, or whether to aggregate the site-specific settings and use them instead of the settings here. Check this box to use the settings here. Uncheck it to use the aggregate.

**Comment by sheilabrennan** [comment]
Hmm, I may be tired, because I still have no idea what that means. 

So if I check that box, will every metadata property selected  be linked across the entire network of sites in the admin views? And will that override any local site settings in that module?

**Comment by mebrett** [comment]
If unchecked, metadata browse options _on the admin side only_ are aggregated from the settings of all the sites using the module.

If checked, _on the admin side only_ the metadata browse is limited by the selections made in the module configuration settings. Site-level settings apply only to the site('s public view) and are not applied on admin-side browse

**Comment by sheilabrennan** [comment]
Thanks @mebrett and @patrickmj, I needed to do more testing to check my assumptions (and I may have found a bug but it's only in 1 site).  

How is this?
If checked, the properties selected below will be linked across all items in the admin views. Any site-specific settings will be visible only on public views.

**Comment by mebrett** [comment]
Clear and concise.

**Comment by patrickmj** [comment]
I'd like to push harder on explaining why things will look different on the admin side and each site's public side.

Maybe

> If checked, the properties selected below will be linked on the admin side, overriding all site-specific settings. Each site's own settings will be reflected on the public side.

**Comment by sheilabrennan** [comment]
That works for me. Thanks, Patrick.

**Comment by patrickmj** [comment]
From #24 convo:

> If checked, the properties selected below will be linked on the admin side, overriding all site-specific settings. Each site's own settings will be reflected on the public side. Otherwise, the admin side will reflect the aggregated settings for all sites; anything selected to be a link in any site will be a link on the admin side.

**Comment by sheilabrennan** [comment]
Perhaps the documentation can help sort that out for admins by providing some examples of those scenarios (not required for release but on the to do list for filling in post-release).

**Comment by patrickmj** [comment]
sounds good to me. I'll add the text above, and close this issue. Any new stuff is appropriate as new issues as needed.
