### ISSUE TITLE
Module causing an error when editing items

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/MetadataBrowse#20]
If I go to edit an item or item set and Metadata Browse, on current commit of branch admin-options, then I get the following: 
![screen shot 2016-08-08 at 11 18 04 am](https://cloud.githubusercontent.com/assets/2314070/17484845/d4e7dc40-5d59-11e6-9174-14f655db8b73.png)

The error is (for Title but it's pretty consistent for all elements): 
`Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #2 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: array_merge(): Argument #1 is not an array in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 137 Warning: in_array() expects parameter 2 to be array, null given in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 151 Silver Blaze`

**Comment by mebrett** [comment]
Note: metadata browse checkbox "use global configuration settings" is NOT checked.

**Comment by patrickmj** [comment]
So far, not able to reproduce. Can you identify any particular characteristics of items that do and do not hit that error?

**Comment by patrickmj** [comment]
Haven't reproduced, but guessing about the error I pushed up a change that might fix it.

**Comment by mebrett** [comment]
Look like it's something specific to the shared omeka-s install. I'm not getting the same error on my other install of S. Could it be interacting with one of the other modules (Installed: CSV Import, DSpace Connector, Fedora Connector, Mapping, Metadata Browse, Sharing, Zotero Import)

**Comment by patrickmj** [comment]
@zerocrates has pointed out some other things amiss in the code, and fixing those will impinge on hunting and fixing this bug, so might be best to set this aside for a while until those are addressed.

**Comment by patrickmj** [comment]
@mebrett Latest on the admin-options branch might fix things. It'll do an upgrade I hope will sort out the array problems

**Comment by mebrett** [comment]
That fixed it. Thank you.
