### ISSUE TITLE
Not linking

### ISSUE THREAD

**Issue by jannellelegg** [omeka-s-modules/MetadataBrowse#22]
Working on test site with metadata browse enabled- selected properties are not generating links unless global admin is checked in settings.

**Comment by patrickmj** [comment]
What branch are you using? This sounds like it might be expected if it is part of #19

**Comment by jannellelegg** [comment]
@mebrett - which branch are we on?

**Comment by mebrett** [comment]
We're on admin-options. 
Based on the comment: "You can switch back and forth whenever you want." I had thought that the admin-options branch would give us the choice between using Global configuration and the aggregate of the individual site settings. 

As it is, with the "use global" not checked, the Metadata Browse module isn't doing _anything,_ not on the admin side and not on individual sites.

**Comment by patrickmj** [comment]
Have the individual sites configured their SearchByMetadata settings? If not, then it's expected that there are no links. If they have, then there should be links.

**Comment by mebrett** [comment]
Yes, the individual sites have Metadata Browse set up. 

Same item, same site.
On branch develop: 
![develop](https://cloud.githubusercontent.com/assets/2314070/17895477/3560aa4e-691b-11e6-92fa-f7e026b5a4c3.png)

on admin-options:
![admin-options](https://cloud.githubusercontent.com/assets/2314070/17895485/3a9ba90a-691b-11e6-9dc1-ff4eedc7cf0d.png)

**Comment by patrickmj** [comment]
just pushed up a change to admin-options that _might_ fix this

other thing to double-check is whether at least one site has dcterms:creator set as searchable

**Comment by mebrett** [comment]
It's working now, on public and admin sides. Thanks

**Comment by patrickmj** [comment]
excellent! There might be some residual iffiness based on what's happened in the db update. If those happen they will likely be fixed by deleting the MetadataBrowse site-specific settings and re-adding them.
