### ISSUE TITLE
Site is not responding to site-specific setting for admin view

### ISSUE THREAD

**Issue by sheilabrennan** [omeka-s-modules/MetadataBrowse#24]
For the Tin Box site, there are no properties selected for Metadata Browse, but the items in its pool have a linked property visible on the admin side.
Site's pool: http://dev.omeka.org/omeka-s/admin/item?site_id=9 
This item, for example, has the Source field is linked: http://dev.omeka.org/omeka-s/admin/item/16776

Public browse responds as expected, there is no linking across properties, http://dev.omeka.org/omeka-s/s/tinbox/page/stuff

I can't figure out how/where to change that Source property selected for metadata browse in admin. It isn't selected at the site or the Global level. And, I have looked at how other sites from this dev install respond to changes in the Global settings, and others have responded as expected. 

I can't tell if this is a real bug or if it is just a peculiarity with one site that might be weird because of all of the version swapping, et al.

**Comment by patrickmj** [comment]
Are you sure that one of those many sites doesn't have Source configured to be linked?

**Comment by mebrett** [comment]
Source was part of Metadata Browse on Site5/Historic Hotels (I poked it yesterday). Just turned it off - Sheila, does that fix it?

**Comment by sheilabrennan** [comment]
It wasn't just Source, it was Source and Subject. But only Source was linked, and only for that pool of items. (although it could have been that there weren't subjects for those other items).

**Comment by sheilabrennan** [comment]
Yes, it does. 

So, does this mean that one site's local settings for this module have global impacts for items viewed in admin?

**Comment by sheilabrennan** [comment]
NB: The Global setting for the module was unchecked.

**Comment by patrickmj** [comment]
Yep. That's exactly the behavior. Sounds like this needs to be added into the description over in #19
