### ISSUE TITLE
CSS breaks browse pages

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#27]
Per investigation here: https://github.com/omeka/omeka-s/issues/919

**Comment by zerocrates** [comment]
This is what was causing the multi-line behavior? That's quite odd... I can easily see it being why yours were all off-center though, so there's that.

**Comment by patrickmj** [comment]
@zerocrates There were other, related, changes in the commit before this, but I don't think that'll make things any less odd.
