### ISSUE TITLE
Compatibility with Omeka S version 1.0.0-beta4?

### ISSUE THREAD

**Issue by hajoki** [omeka-s-modules/MetadataBrowse#34]
Is there a version of the module Metadata Browse compatible with Omeka S version 1.0.0-beta4?
- With Metadata Browse version 1.0.0-beta2, the links installed by the module do not filter according to any query, they bring to the page of all items. 
- With Metadata Browse version 1.0.0-beta3, the module needs the not released yet Omeka S version 1.0.0-beta5 to function. 
Or shall I wait for the next Omeka S release?
Thanks!

**Comment by patrickmj** [comment]
Thanks. It looks like there's also a regression on the latest develop of Omeka S. It might be best, then to wait for the next Omeka S release, last predicted with two or three weeks.

**Comment by hajoki** [comment]
ok, thanks for the info!

**Comment by patrickmj** [comment]
@hajoki  Have you tried the release candidate to see if it works?
