### ISSUE TITLE
CSS messes up multiple references

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#39]
Following up https://github.com/omeka/omeka-s/issues/1104#issuecomment-339139450

When the property IS part of the metadatabrowse config, it's okay. But when not, the misalignment happens. Eliminating the offending CSS, though, prevents the link to all same values from appearing properly.

**Comment by zerocrates** [comment]
I've got some styling/markup changes to the resource values to talk over with Kim that may make this easier to deal with.

**Comment by patrickmj** [comment]
Also messes with privacy icon. see  https://github.com/omeka/omeka-s/issues/1093#issuecomment-339478508
