### ISSUE TITLE
Breaks on apostrophe

### ISSUE THREAD

**Issue by ckarpinski** [omeka-s-modules/MetadataBrowse#47]
I have subject names with the last name O'Brien and the subject field set to use Metadata Browse. It does not work. It returns 0 items. I can go to an item with that subject, see the subject is linked there in the page but when I click it, it returns 0.

**Comment by zerocrates** [comment]
Is the site accessible so we can see the link that's being generated?

I can't immediately reproduce your problem, so it's not as simple as just "apostrophes are broken always."

Also, good to make sure, what version of this module and of Omeka S are you using?

**Comment by ckarpinski** [comment]
Omeka S 3.0.2
MetadataBrowse 1.4.0

It is breaking on names O'Brien - it turns these into a link with the value only as the letter O, it doesn't include the 'Brien like this
https://theredwoodhouse.org/s/redwoodhouse/item?Search=&property%5B0%5D%5Bproperty%5D=3&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=O

The site is only viewable by logging in, I could create you a login to view it? Do you need to see the Admin or would just seeing the pages of the site with the metadata be enough?

**Comment by zerocrates** [comment]
Sharing the link itself was very helpful.

I was able to reproduce this with different settings: I assume you have "Direct Links" enabled in the module's configuration page? There's an issue specifically in that mode with how the link is generated that would particularly affect apostrophes, which is fixed.

I just made a fix for that problem, which should resolve this issue for you.

**Comment by ckarpinski** [comment]
Yes I had that box checked. 
I tried updating the plugin to the code that is here and it breaks the site completely - I downloaded the zip edited the unzipped file and put it in the modules folder.....

**Comment by zerocrates** [comment]
What did you do exactly? If you downloaded this updated version, it needs to replace the existing MetadataBrowse folder you have in your modules folder, and the version from Github won't have the correct folder name. You'd need to delete the old MetadataBrowse folder you have, unzip the new one, and since you're getting it direct from Github, you need to change the name of the outer folder from whatever Github has it as (something like "MetadataBrowse-develop" probably) to just "MetadataBrowse"

**Comment by ckarpinski** [comment]
That is what I did, I downloaded the zip, renamed the extracted folder to MetadataBrowse and replaced it for the one I had currently on my site in the modules folder.. I will try again.

**Comment by ckarpinski** [comment]
Worked this time. no idea what was different. and the links for O'Brien are working now, thank you!!
