### ISSUE TITLE
Admin Incompatibility with Omeka 3.2 annotations ?

### ISSUE THREAD

**Issue by AlyxTaj** [omeka-s-modules/MetadataBrowse#49]
Hello,

We have just updated our Omeka digital library to the 3.2 version, eager to test the annotation function.

We have met a small issue when annotating some content. From what we gathered, adding an annotation with a property that is used in the global settings of Metadata Browse (for example in our case the 'dcterms:type' property) to any type of value results in an error that blocks access to the admin view page of the resource (the public view and the admin edit page however are still accessible).
No such issue appears when adding an unbrowsable annotation to a value with a browsable property. There is also no issue on the public page of the resource when a property used as annotation is browsable in the site configuration.

The error log reads as such:

> Laminas\Router\Exception\InvalidArgumentException: Missing parameter "controller" in /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/Segment.php:310 Stack trace: #0 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/Segment.php(420): Laminas\Router\Http\Segment->buildPath(Array, Array, false, false, Array) #1 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/Part.php(204): Laminas\Router\Http\Segment->assemble(Array, Array) #2 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/TreeRouteStack.php(371): Laminas\Router\Http\Part->assemble(Array, Array) #3 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/Part.php(217): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array) #4 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-router/src/Http/TreeRouteStack.php(392): Laminas\Router\Http\Part->assemble(Array, Array) #5 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Helper/Url.php(105): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array) #6 /webhome/omeka-s/www/omeka-s/application/src/View/Helper/Url.php(34): Laminas\View\Helper\Url->__invoke('admin/default', Array, Array, false) #7 /webhome/omeka-s/www/omeka-s/modules/MetadataBrowse/Module.php(260): Omeka\View\Helper\Url->__invoke('admin/default', Array, Array) #8 /webhome/omeka-s/www/omeka-s/modules/MetadataBrowse/Module.php(225): MetadataBrowse\Module->literalSearchUrl(Object(Omeka\View\Helper\Url), Array, 8, 'test') #9 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): MetadataBrowse\Module->repValueHtml(Object(Laminas\EventManager\Event)) #10 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(143): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event)) #11 /webhome/omeka-s/www/omeka-s/application/src/Api/Representation/ValueRepresentation.php(62): Laminas\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject)) #12 /webhome/omeka-s/www/omeka-s/application/view/common/resource-values.phtml(51): Omeka\Api\Representation\ValueRepresentation->asHtml() #13 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/webhome/omeka-...') #14 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, Array) #15 [internal function]: Laminas\View\Helper\Partial->__invoke('common/resource...') #16 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array) #17 /webhome/omeka-s/www/omeka-s/application/view/common/value-annotation-resource-values.phtml(1): Laminas\View\Renderer\PhpRenderer->__call('partial', Array) #18 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/webhome/omeka-...') #19 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, Array) #20 /webhome/omeka-s/www/omeka-s/application/src/Api/Representation/ValueAnnotationRepresentation.php(24): Laminas\View\Helper\Partial->__invoke('common/value-an...', Array) #21 /webhome/omeka-s/www/omeka-s/application/view/common/resource-values.phtml(60): Omeka\Api\Representation\ValueAnnotationRepresentation->displayValues() #22 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/webhome/omeka-...') #23 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, Array) #24 /webhome/omeka-s/www/omeka-s/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(493): Laminas\View\Helper\Partial->__invoke('common/resource...', Array) #25 /webhome/omeka-s/www/omeka-s/application/view/omeka/admin/item/show.phtml(34): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues() #26 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/webhome/omeka-...') #27 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL) #28 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel)) #29 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel)) #30 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel)) #31 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent)) #32 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent)) #33 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent)) #34 /webhome/omeka-s/www/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent)) #35 /webhome/omeka-s/www/omeka-s/index.php(21): Laminas\Mvc\Application->run() #36 {main}

Of course, we are going to try and avoid using such properties for annotations and/or change our browsing settings to adapt, but in any case, we wanted to signal the problem.
Thank you for your work.

Alyx

**Comment by zerocrates** [comment]
Thanks for reporting this issue.

We have updates to this module that should fix this problem that should be released soon. We'll keep you posted.

**Comment by zerocrates** [comment]
The code that fixes this is currently on the `develop` branch if you're comfortable with using Git and would like to try it out.

**Comment by AlyxTaj** [comment]
Thank you @zerocrates we just checked out the develop branch and it seems to work well! No problem accessing our contents from admin.

**Comment by zerocrates** [comment]
Thanks for letting us know.

This fix will release as version 1.5.0 of MetadataBrowse, which will require S 3.2.
