### ISSUE TITLE
Test metadata browse

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#5]
on current master branch, install and configure properties to produce a search. links should go to the list of other items or item sets with the same value. 

N.B. it doesn't yet work for values of type Resource

Try it in different browsers, especially the configuration, and changing around the configuration.

@alyssafahringer @mebrett

**Comment by alyssafahringer** [comment]
I haven't run into any problems yet, but I'll play around with it more when I get back on Monday.

**Comment by alyssafahringer** [comment]
In Firefox, Safari, and Chrome, when I configure the module and delete all the Dublin Core properties that had previously been in use for the module, I get the following error when looking at items or item sets:
Warning: in_array() expects parameter 2 to be array, null given in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 73

**Comment by zerocrates** [comment]
Confirm, and also trying to save the configure page with no properties on it gives me a notice immediately:

> Notice: Undefined index: propertyIds in /var/www/localhost/htdocs/omeka-s/modules/MetadataBrowse/Module.php on line 43

**Comment by patrickmj** [comment]
@mebrett @alyssafahringer Latest master branch of Metadata browse should 1) address the warnings and 2) add in functionality for Resource Values.

Will be good to 
1. uninstall and reinstall the module
2. pull the latest Omeka S develop branch
3. make an item or 2 or 3 that has some property (e.g., Relation) assigned to an Omeka Resource

On that item, the metadata browse link should go to a browse page for the targets of the property (e.g., Relation)
