### ISSUE TITLE
MB shows on user accounts without permission

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/MetadataBrowse#51]
Metadata Browse shows up in the site-specific menu on lower-level user accounts (researcher, author, reviewer). 
![MBissue1](https://user-images.githubusercontent.com/28012148/173688483-f81d3182-e6b8-43a9-815d-88a452449a9b.PNG)

Clicking makes an error page:
![MBissue2](https://user-images.githubusercontent.com/28012148/173688485-3e7cba4a-fe10-47f3-a2e0-317ce3ab3010.PNG)

Works at Editor level and above. Appears at the Editor level even if that user isn't added to the specific site, so that may be a problem too. 

Appears alongside other modules and works fine at the Supervisor level, which I assume is expected behaviour.

**Comment by zerocrates** [comment]
It's purposely allowed to Editors. Now, the "purpose" behind that "purposely"... no comment at this time.

I probably just need to add the nav params to make this check for the permission when deciding whether to show the entry.

**Comment by allanaaa** [comment]
Okay! It's a bit weird that I (at Editor level) can change a site's MB options but nothing else, but I will leave that to your no comment.

**Comment by zerocrates** [comment]
We can look at making it depend on the site-specific Admin permission level or something similar instead.

The menu option appearing when it shouldn't is a true bug that applies regardless of that adjustment though.
