### ISSUE TITLE
Metadata Browse multiple values

### ISSUE THREAD

**Issue by Kquotap** [omeka-s-modules/MetadataBrowse#53]
Hi new to all of this but im working with metadata browse on Omeka-s and it will work with fields with single values but not with multiple values. I don't see any way to change the options. 

Thanks for any help happy to answer more questions to help figure this out. New to omeka so sorry if this is an easy fix.

**Comment by zerocrates** [comment]
So, what's not working here? I don't know that I have a clear sense of the issue you're reporting.

**Comment by Kquotap** [comment]
I installed the metadata browse module on my test site. It is working fine for metadata with one value, but when I try to add fields like dcterms:subject, which has multiple values it will not work. So I was wondering if I was missing something in the set up that will allow for fields with multiple values. 

Like if the item has one author it will work fine, it gives a hyper link but if it has two the option to click on a name and find other items goes away.

**Comment by zerocrates** [comment]
It should just work with multiple values.

You're saying that once you have more than one value for a property there's just no metadata browse link at all? This is the same on the admin and public sides?

What versions of the Omeka S core and Metadata Browse are you using?

**Comment by Kquotap** [comment]
I think it is working now. We had things in the same field with different separators but switched to individual fields on the metadata record  on the edit pages and it separated them out and made them searchable. 

Thanks for listening to this new person's issue and answering
