### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/MetadataBrowse#8]
On commit 622f53c9e8af4f56c228b48913024816c9b61d81; when I go to uninstall Metadata Browse, I get the error "Fatal error: Call to a member function delete() on a non-object in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 35"

(On branch Develop of OmekaS, commit  ca41dbee051b99a86228f78bfc98e92e4fe07471)

**Comment by patrickmj** [comment]
curious, but hopefully latest push will solve it.

**Comment by mebrett** [comment]
That fixed it.
